---
- name: "Deploy Mongodb"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: "Install Mongodb"
      when: inv_install_mongodb | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host_system_users: "{{ inv_prepare_host_mongodb_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_mongodb_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_mongodb_cert_bundles is defined
          vars:
            add_certificates_bundle_name: "{{ bundle.name }}"
            add_certificates_bundle_type: "{{ bundle.type }}"
            add_certificates_bundle_src: "{{ bundle.src }}"
            add_certificates_bundle_dest: "{{ bundle.dest }}"
            add_certificates_bundle_src_user: "{{ bundle.src_user }}"
            add_certificates_bundle_src_password: "{{ bundle.src_password }}"
            add_certificates_bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates_bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates_bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_mongodb"
          tags:
            - "labocbz.install_mongodb"
          vars:
            install_mongodb_version: "{{ inv_install_mongodb_version }}"
            install_mongodb_distribution_release: "{{ inv_install_mongodb_distribution_release }}"
            install_mongodb_architecture: "{{ inv_install_mongodb_architecture }}"
            install_mongodb_db_user: "{{ inv_install_mongodb_db_user }}"
            install_mongodb_db_group: "{{ inv_install_mongodb_db_group }}"
            install_mongodb_db_path: "{{ inv_install_mongodb_db_path }}"
            install_mongodb_log_path: "{{ inv_install_mongodb_log_path }}"
            install_mongodb_log_file: "{{ inv_install_mongodb_log_file }}"
            install_mongodb_ssl_path: "{{ inv_install_mongodb_ssl_path }}"
            install_mongodb_bind: "{{ inv_install_mongodb_bind }}"
            install_mongodb_port: "{{ inv_install_mongodb_port }}"
            install_mongodb_ssl: "{{ inv_install_mongodb_ssl }}"
            install_mongodb_ssl_cert: "{{ inv_install_mongodb_ssl_cert }}"
            install_mongodb_ssl_key: "{{ inv_install_mongodb_ssl_key }}"
            install_mongodb_ssl_pem_key_file: "{{ inv_install_mongodb_ssl_pem_key_file }}"
            install_mongodb_ssl_client_auth: "{{ inv_install_mongodb_ssl_client_auth }}"
            install_mongodb_ssl_ca: "{{ inv_install_mongodb_ssl_ca }}"
            install_mongodb_admin_login: "{{ inv_install_mongodb_admin_login }}"
            install_mongodb_admin_password: "{{ inv_install_mongodb_admin_password }}"
            install_mongodb_ssl_ca_file: "{{ inv_install_mongodb_ssl_ca_file }}"
          ansible.builtin.include_role:
            name: "labocbz.install_mongodb"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            logrotate_configurations: "{{ inv_logrotate_mongodb_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
