---
- name: "Deploy Mongodb"
  hosts: "{{ tower_env | default([]) }}"
  gather_facts: true
  become: true
  become_method: sudo
  become_user: root

  tasks:
    - name: "Install Mongodb"
      when: inv_install_mongodb | default(false)
      block:
        - name: "Include labocbz.prepare_host"
          tags:
            - "labocbz.prepare_host"
          vars:
            prepare_host__system_users: "{{ inv_prepare_host__mongodb_system_users }}"
          ansible.builtin.include_role:
            name: "labocbz.prepare_host"

        - name: "Include labocbz.add_certificates"
          tags:
            - "labocbz.add_certificates"
          loop: "{{ inv_mongodb_cert_bundles }}"
          loop_control:
            loop_var: bundle
          when: inv_mongodb_cert_bundles is defined
          vars:
            add_certificates__bundle_name: "{{ bundle.name }}"
            add_certificates__bundle_type: "{{ bundle.type }}"
            add_certificates__bundle_src: "{{ bundle.src }}"
            add_certificates__bundle_dest: "{{ bundle.dest }}"
            add_certificates__bundle_src_user: "{{ bundle.src_user }}"
            add_certificates__bundle_src_password: "{{ bundle.src_password }}"
            add_certificates__bundle_dest_user: "{{ bundle.dest_user }}"
            add_certificates__bundle_dest_group: "{{ bundle.dest_group }}"
            add_certificates__bundle_dest_mode: "{{ bundle.dest_mode }}"
          ansible.builtin.include_role:
            name: "labocbz.add_certificates"

        - name: "Include labocbz.install_mongodb"
          tags:
            - "labocbz.install_mongodb"
          vars:
            install_mongodb__version: "{{ inv_install_mongodb__version }}"
            install_mongodb__distribution_release: "{{ inv_install_mongodb__distribution_release }}"
            install_mongodb__architecture: "{{ inv_install_mongodb__architecture }}"
            install_mongodb__db_user: "{{ inv_install_mongodb__db_user }}"
            install_mongodb__db_group: "{{ inv_install_mongodb__db_group }}"
            install_mongodb__db_path: "{{ inv_install_mongodb__db_path }}"
            install_mongodb__log_path: "{{ inv_install_mongodb__log_path }}"
            install_mongodb__log_file: "{{ inv_install_mongodb__log_file }}"
            install_mongodb__ssl_path: "{{ inv_install_mongodb__ssl_path }}"
            install_mongodb__bind: "{{ inv_install_mongodb__bind }}"
            install_mongodb__port: "{{ inv_install_mongodb__port }}"
            install_mongodb__ssl: "{{ inv_install_mongodb__ssl }}"
            install_mongodb__ssl_cert: "{{ inv_install_mongodb__ssl_cert }}"
            install_mongodb__ssl_key: "{{ inv_install_mongodb__ssl_key }}"
            install_mongodb__ssl_pem_key_file: "{{ inv_install_mongodb__ssl_pem_key_file }}"
            install_mongodb__ssl_client_auth: "{{ inv_install_mongodb__ssl_client_auth }}"
            install_mongodb__ssl_ca: "{{ inv_install_mongodb__ssl_ca }}"
            install_mongodb__admin_login: "{{ inv_install_mongodb__admin_login }}"
            install_mongodb__admin_password: "{{ inv_install_mongodb__admin_password }}"
            install_mongodb__ssl_ca_file: "{{ inv_install_mongodb__ssl_ca_file }}"
          ansible.builtin.include_role:
            name: "labocbz.install_mongodb"

        - name: "Include labocbz.add_logrotate_confs"
          tags:
            - "labocbz.add_logrotate_confs"
          vars:
            add_logrotate_confs__files: "{{ inv_add_logrotate_confs__mongodb_configurations }}"
          ansible.builtin.include_role:
            name: "labocbz.add_logrotate_confs"
